//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOAPe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;
        ///               xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;t:RequestServerVersion Version=&quot;Exchange2010_SP2&quot;/&gt;
        ///  &lt;/soap:Header&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;ConvertId xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;
        ///               xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;
        ///               DestinationFormat=&quot;%DEST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EWSConvertIDTemplate {
            get {
                return ResourceManager.GetString("EWSConvertIDTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ExchangeImpersonation xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;
        ///  &lt;ConnectingSID&gt;
        ///    &lt;IMPERSONATIONTAG&gt;%IMPERSONATIONID%&lt;/IMPERSONATIONTAG&gt;
        ///  &lt;/ConnectingSID&gt;
        ///&lt;/ExchangeImpersonation&gt;
        ///.
        /// </summary>
        internal static string EWSImpersonationHeader {
            get {
                return ResourceManager.GetString("EWSImpersonationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:m=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot; xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;m:SendNotificationResult&gt;
        ///      &lt;m:SubscriptionStatus&gt;OK&lt;/m:SubscriptionStatus&gt;
        ///    &lt;/m:SendNotificationResult&gt;
        ///  &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string EWSSendNotificationResult {
            get {
                return ResourceManager.GetString("EWSSendNotificationResult", resourceCulture);
            }
        }
    }
}
